name = "coffee"
main = "./dist/_worker.js/index.js"
upload_source_maps = true
compatibility_date = "2025-04-08"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true

[vars]
AWS_REGION = "eu-central-1"
ORIGIN = "https://centralbeans.com"
RELYING_PARTY_ID = "centralbeans.com"
