name = "coffee"
main = "./dist/_worker.js/index.js"
upload_source_maps = true
compatibility_date = "2025-04-08"
compatibility_flags = ["nodejs_compat"]
route = { pattern = "centralbeans.com", zone_name = "centralbeans.com", custom_domain = true }
version_metadata = { binding = "CF_VERSION_METADATA" }

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true

[vars]
AWS_REGION = "eu-central-1"
ORIGIN = "https://centralbeans.com"
RELYING_PARTY_ID = "centralbeans.com"

[[ratelimits]]
name = "REGISTRATION_CODE_RATE_LIMITER"
namespace_id = "1001"

[ratelimits.simple]
limit = 1
period = 60

[[ratelimits]]
name = "NEW_USER_RATE_LIMITER"
namespace_id = "1002"

[ratelimits.simple]
limit = 1
period = 60
