AWSTemplateFormatVersion: '2010-09-09'
Description: CloudWatch Alarm for Trigger Github Action errors

Resources:
  triggerGithubActionErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: triggerGithubActionErrors
      Tags: []
      ActionsEnabled: true
      OKActions: []
      AlarmActions:
        - arn:aws:sns:eu-central-1:781346609033:triggerGithubActionErrors
      InsufficientDataActions: []
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Dimensions:
        - Name: FunctionName
          Value: triggerGithubAction
      Period: 300
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
