AWSTemplateFormatVersion: '2010-09-09'
Description: Schedules for crawling roaster webshops

Parameters:
  RecordLambdaArn:
    Type: String
    Default: 'arn:aws:lambda:eu-central-1:781346609033:function:recordRoasterWebshop'
    Description: ARN of the Lambda function to trigger
  FlexibilityWindow:
    Type: String
    Default: '5'
    Description: Flexibility window in minutes

Resources:
  SchedulerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource:
                  - !Ref RecordLambdaArn
                  - !Sub '${RecordLambdaArn}:*'

  SheepAndRavenSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: SheepAndRavenSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(0 0 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 6}'

  ElCafeteroSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: ElCafeteroSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(10 0 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 7}'

  TypikaSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: TypikaSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(20 0 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 14}'

  BeMyBeanSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: BeMyBeanSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(30 0 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 39}'

  HeresySchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: HeresySchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(40 0 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 65}'

  KlaroSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: KlaroSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(50 0 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 70}'

  SpojkaSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: SpojkaSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(0 1 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 82}'

  # MeronSchedule:
  #   Type: AWS::Scheduler::Schedule
  #   Properties:
  #     Name: MeronSchedule
  #     FlexibleTimeWindow:
  #       Mode: 'FLEXIBLE'
  #       MaximumWindowInMinutes: !Ref FlexibilityWindow
  #     ScheduleExpression: 'cron(10 1 ? * MON *)'
  #     Target:
  #       Arn: !Ref RecordLambdaArn
  #       RoleArn: !GetAtt SchedulerExecutionRole.Arn
  #       Input: '{"roasterId": 252}'

  FathersSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: FathersSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(20 1 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 277}'

  # PaleSchedule:
  #   Type: AWS::Scheduler::Schedule
  #   Properties:
  #     Name: PaleSchedule
  #     ScheduleExpression: "cron(90 0 ? * MON *)"
  #     Target:
  #       Arn: !Ref RecordLambdaArn
  #       RoleArn: !GetAtt SchedulerExecutionRole.Arn
  #       Input: '{"roasterId": 278}'

  BaniBeansSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: BaniBeansSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(30 1 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 285}'

  StowSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: StowSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(40 1 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 286}'

  KavaFamilySchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: KavaFamilySchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(50 1 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 287}'

  NordbeansSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: NordbeansSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(0 2 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 288}'

  RoastGrindBrewSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: RoastGrindBrewSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(10 2 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 290}'

  TesoSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: TesoSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(20 2 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 291}'

  CraftBeansSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: CraftBeansSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(30 2 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 297}'

  LaCabraSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: LaCabraSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(40 2 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 10}'

  AMOCSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: AMOCSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(50 2 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 94}'

  aprilSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: aprilSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(0 3 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 47}'

  FriedhatsSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: FriedhatsSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(10 3 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 12}'

  NaughtyDogSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: NaughtyDogSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(20 3 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 310}'

  CoffeeCollectiveSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: CoffeeCollectiveSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(30 3 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 11}'

  ManhattanSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: ManhattanSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(40 3 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 305}'

  PikolaSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: PikolaSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(50 3 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 265}'

  DaturaSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: DaturaSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(0 4 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 304}'

  DoubleshotSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: DoubleshotSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(10 4 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 311}'

  NolensVolensSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: NolensVolensSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(20 4 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 258}'

  SerceKawySchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: SerceKawySchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(30 4 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 314}'

  BeBerrySchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: BeBerrySchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(40 4 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 315}'

  LenSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: LenSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(50 4 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 317}'

  MiaSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: MiaSchedule
      FlexibleTimeWindow:
        Mode: 'FLEXIBLE'
        MaximumWindowInMinutes: !Ref FlexibilityWindow
      ScheduleExpression: 'cron(0 5 ? * MON *)'
      Target:
        Arn: !Ref RecordLambdaArn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
        Input: '{"roasterId": 312}'
