name: Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Check changed files
        id: changed-files-yaml
        uses: tj-actions/changed-files@v47
        with:
          files_yaml: |
            coffee-admin:
              - .github/workflows/deploy.yml
              - packages/coffee-admin/package.json
              - packages/coffee-admin/index.js
              - packages/coffee-admin/.yarnrc-lambda.yml
              - packages/coffee-admin/src/**
              - packages/coffee.chealt.com/data/roasters.json
            image-processor:
              - packages/image-processor/package.json
              - packages/image-processor/.yarnrc-lambda.yml
              - packages/image-processor/src/**
            image-text-interpreter:
              - packages/image-text-interpreter/package.json
              - packages/image-text-interpreter/.yarnrc-lambda.yml
              - packages/image-text-interpreter/src/**
            record-webshop-item:
              - packages/record-webshop-item/package.json
              - packages/record-webshop-item/.yarnrc-lambda.yml
              - packages/record-webshop-item/src/**
            record-webshop-item-details:
              - packages/record-webshop-item-details/package.json
              - packages/record-webshop-item-details/.yarnrc-lambda.yml
              - packages/record-webshop-item-details/src/**
            webshop-item-processor:
              - packages/coffee.chealt.com/data/**
              - packages/webshop-item-processor/package.json
              - packages/webshop-item-processor/.yarnrc-lambda.yml
              - packages/webshop-item-processor/src/**
            webshop-processor:
              - packages/webshop-processor/package.json
              - packages/webshop-processor/.yarnrc-lambda.yml
              - packages/webshop-processor/src/**
      - name: coffee-admin
        id: coffee-admin
        if: steps.changed-files-yaml.outputs.coffee-admin_any_changed == 'true'
        run: |
          yarn workspace @chealt/coffee-admin build
          version=$(yarn workspace @chealt/coffee-admin deploy | jq -r '.Version')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Release coffee-admin
        if: steps.changed-files-yaml.outputs.coffee-admin_any_changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '@chealt/coffee-admin@${{ steps.coffee-admin.outputs.version }}'
          release_name: Release @chealt/coffee-admin v${{ steps.coffee-admin.outputs.version }}
          draft: false
          prerelease: false
      - name: image-processor
        id: image-processor
        if: steps.changed-files-yaml.outputs.image-processor_any_changed == 'true'
        run: |
          yarn workspace @chealt/image-processor build
          version=$(yarn workspace @chealt/image-processor deploy | jq -r '.Version')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Release image-processor
        if: steps.changed-files-yaml.outputs.image-processor_any_changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '@chealt/image-processor@${{ steps.image-processor.outputs.version }}'
          release_name: Release @chealt/image-processor v${{ steps.image-processor.outputs.version }}
          draft: false
          prerelease: false
      - name: image-text-interpreter
        id: image-text-interpreter
        if: steps.changed-files-yaml.outputs.image-text-interpreter_any_changed == 'true'
        run: |
          yarn workspace @chealt/image-text-interpreter build
          version=$(yarn workspace @chealt/image-text-interpreter deploy | jq -r '.Version')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Release image-text-interpreter
        if: steps.changed-files-yaml.outputs.image-text-interpreter_any_changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '@chealt/image-text-interpreter@${{ steps.image-text-interpreter.outputs.version }}'
          release_name: Release @chealt/image-text-interpreter v${{ steps.image-text-interpreter.outputs.version }}
          draft: false
          prerelease: false
      - name: record-webshop-item
        id: record-webshop-item
        if: steps.changed-files-yaml.outputs.record-webshop-item_any_changed == 'true'
        run: |
          yarn workspace @chealt/record-webshop-item build
          version=$(yarn workspace @chealt/record-webshop-item deploy | jq -r '.Version')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Release record-webshop-item
        if: steps.changed-files-yaml.outputs.record-webshop-item_any_changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '@chealt/record-webshop-item@${{ steps.record-webshop-item.outputs.version }}'
          release_name: Release @chealt/record-webshop-item v${{ steps.record-webshop-item.outputs.version }}
          draft: false
          prerelease: false
      - name: record-webshop-item-details
        id: record-webshop-item-details
        if: steps.changed-files-yaml.outputs.record-webshop-item-details_any_changed == 'true'
        run: |
          yarn workspace @chealt/record-webshop-item-details build
          version=$(yarn workspace @chealt/record-webshop-item-details deploy | jq -r '.Version')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Release record-webshop-item-details
        if: steps.changed-files-yaml.outputs.record-webshop-item-details_any_changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '@chealt/record-webshop-item-details@${{ steps.record-webshop-item-details.outputs.version }}'
          release_name: Release @chealt/record-webshop-item-details v${{ steps.record-webshop-item-details.outputs.version }}
          draft: false
          prerelease: false
      - name: webshop-item-processor
        id: webshop-item-processor
        if: steps.changed-files-yaml.outputs.webshop-item-processor_any_changed == 'true'
        run: |
          yarn workspace @chealt/webshop-item-processor build
          version=$(yarn workspace @chealt/webshop-item-processor deploy | jq -r '.Version')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Release webshop-item-processor
        if: steps.changed-files-yaml.outputs.webshop-item-processor_any_changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '@chealt/webshop-item-processor@${{ steps.webshop-item-processor.outputs.version }}'
          release_name: Release @chealt/webshop-item-processor v${{ steps.webshop-item-processor.outputs.version }}
          draft: false
          prerelease: false
      - name: webshop-processor
        id: webshop-processor
        if: steps.changed-files-yaml.outputs.webshop-processor_any_changed == 'true'
        run: |
          yarn workspace @chealt/webshop-processor build
          version=$(yarn workspace @chealt/webshop-processor deploy | jq -r '.Version')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Release webshop-processor
        if: steps.changed-files-yaml.outputs.webshop-processor_any_changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '@chealt/webshop-processor@${{ steps.webshop-processor.outputs.version }}'
          release_name: Release @chealt/webshop-processor v${{ steps.webshop-processor.outputs.version }}
          draft: false
          prerelease: false
