name: Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Check changed files
        id: changed-files-yaml
        uses: tj-actions/changed-files@v47
        with:
          files_yaml: |
            coffee-admin:
              - .github/workflows/deploy.yml
              - packages/coffee-admin/package.json
              - packages/coffee-admin/index.js
              - packages/coffee-admin/.yarnrc-lambda.yml
              - packages/coffee-admin/src/**
              - packages/coffee.chealt.com/data/roasters.json
            image-processor:
              - packages/image-processor/package.json
              - packages/image-processor/.yarnrc-lambda.yml
              - packages/image-processor/src/**
            image-text-interpreter:
              - packages/image-text-interpreter/package.json
              - packages/image-text-interpreter/.yarnrc-lambda.yml
              - packages/image-text-interpreter/src/**
            record-webshop-item:
              - packages/record-webshop-item/package.json
              - packages/record-webshop-item/.yarnrc-lambda.yml
              - packages/record-webshop-item/src/**
            record-webshop-item-details:
              - packages/record-webshop-item-details/package.json
              - packages/record-webshop-item-details/.yarnrc-lambda.yml
              - packages/record-webshop-item-details/src/**
            webshop-item-processor:
              - packages/coffee.chealt.com/data/**
              - packages/webshop-item-processor/package.json
              - packages/webshop-item-processor/.yarnrc-lambda.yml
              - packages/webshop-item-processor/src/**
            webshop-processor:
              - packages/webshop-processor/package.json
              - packages/webshop-processor/.yarnrc-lambda.yml
              - packages/webshop-processor/src/**
      - name: coffee-admin
        id: coffee-admin
        if: steps.changed-files-yaml.outputs.coffee-admin_any_changed == 'true'
        run: |
          yarn workspace @chealt/coffee-admin build
          yarn workspace @chealt/coffee-admin deploy >> "$GITHUB_OUTPUT"
      - name: Release coffee-admin
        if: steps.changed-files-yaml.outputs.coffee-admin_any_changed == 'true'
        run: echo ${{ fromJSON(steps.coffee-admin.outputs).Version }}
        # uses: actions/create-release@v1
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
        #   tag_name: ${{ github.ref }}
        #   release_name: Release ${{ github.ref }}
        #   draft: false
        #   prerelease: false
      - name: image-processor
        if: steps.changed-files-yaml.outputs.image-processor_any_changed == 'true'
        run: |
          yarn workspace @chealt/image-processor build
          yarn workspace @chealt/image-processor deploy
      - name: image-text-interpreter
        if: steps.changed-files-yaml.outputs.image-text-interpreter_any_changed == 'true'
        run: |
          yarn workspace @chealt/image-text-interpreter build
          yarn workspace @chealt/image-text-interpreter deploy
      - name: record-webshop-item
        if: steps.changed-files-yaml.outputs.record-webshop-item_any_changed == 'true'
        run: |
          yarn workspace @chealt/record-webshop-item build
          yarn workspace @chealt/record-webshop-item deploy
      - name: record-webshop-item-details
        if: steps.changed-files-yaml.outputs.record-webshop-item-details_any_changed == 'true'
        run: |
          yarn workspace @chealt/record-webshop-item-details build
          yarn workspace @chealt/record-webshop-item-details deploy
      - name: webshop-item-processor
        if: steps.changed-files-yaml.outputs.webshop-item-processor_any_changed == 'true'
        run: |
          yarn workspace @chealt/webshop-item-processor build
          yarn workspace @chealt/webshop-item-processor deploy
      - name: webshop-processor
        if: steps.changed-files-yaml.outputs.webshop-processor_any_changed == 'true'
        run: |
          yarn workspace @chealt/webshop-processor build
          yarn workspace @chealt/webshop-processor deploy
