name: Deploy
on:
  push:
    branches:
      - main
  # Trigger when the cron workflow completes
  workflow_run:
    workflows: ['release']
    types:
      - completed
permissions:
  contents: write
concurrency:
  group: deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Check changed files
        id: changed-files-yaml
        uses: tj-actions/changed-files@v47
        with:
          files_yaml: |
            create-user:
              - yarn.lock
              - .github/workflows/deploy.yml
              - packages/create-user/package.json
              - packages/create-user/.yarnrc-lambda.yml
              - packages/create-user/src/**
            delete-user:
              - yarn.lock
              - .github/workflows/deploy.yml
              - packages/delete-user/package.json
              - packages/delete-user/.yarnrc-lambda.yml
              - packages/delete-user/src/**
            flag-removed:
              - yarn.lock
              - .github/workflows/deploy.yml
              - packages/flag-removed/package.json
              - packages/flag-removed/.yarnrc-lambda.yml
              - packages/flag-removed/src/**
            image-processor:
              - yarn.lock
              - .github/workflows/deploy.yml
              - packages/image-processor/package.json
              - packages/image-processor/.yarnrc-lambda.yml
              - packages/image-processor/src/**
            image-text-interpreter:
              - yarn.lock
              - .github/workflows/deploy.yml
              - packages/image-text-interpreter/package.json
              - packages/image-text-interpreter/.yarnrc-lambda.yml
              - packages/image-text-interpreter/src/**
            import-currencies:
              - yarn.lock
              - .github/workflows/deploy.yml
              - packages/import-currencies/package.json
              - packages/import-currencies/.yarnrc-lambda.yml
              - packages/import-currencies/src/**
            invoke-flag-removed:
              - yarn.lock
              - .github/workflows/deploy.yml
              - packages/invoke-flag-removed/package.json
              - packages/invoke-flag-removed/.yarnrc-lambda.yml
              - packages/invoke-flag-removed/src/**
            notifications:
              - yarn.lock
              - .github/workflows/deploy.yml
              - packages/coffee.chealt.com/data/**
              - packages/notifications/package.json
              - packages/notifications/.yarnrc-lambda.yml
              - packages/notifications/src/**
            record-roaster-webshop:
              - yarn.lock
              - .github/workflows/deploy.yml
              - packages/coffee.chealt.com/data/roasters.json
              - packages/record-roaster-webshop/package.json
              - packages/record-roaster-webshop/.yarnrc-lambda.yml
              - packages/record-roaster-webshop/src/**
            record-webshop-item:
              - yarn.lock
              - .github/workflows/deploy.yml
              - packages/record-webshop-item/package.json
              - packages/record-webshop-item/.yarnrc-lambda.yml
              - packages/record-webshop-item/src/**
            record-webshop-item-details:
              - yarn.lock
              - .github/workflows/deploy.yml
              - packages/record-webshop-item-details/package.json
              - packages/record-webshop-item-details/.yarnrc-lambda.yml
              - packages/record-webshop-item-details/src/**
            register-new-user:
              - yarn.lock
              - .github/workflows/deploy.yml
              - packages/register-new-user/package.json
              - packages/register-new-user/.yarnrc-lambda.yml
              - packages/register-new-user/src/**
            send-registration-code:
              - yarn.lock
              - .github/workflows/deploy.yml
              - packages/send-registration-code/package.json
              - packages/send-registration-code/.yarnrc-lambda.yml
              - packages/send-registration-code/src/**
            webshop-item-processor:
              - yarn.lock
              - .github/workflows/deploy.yml
              - packages/coffee.chealt.com/data/**
              - packages/webshop-item-processor/package.json
              - packages/webshop-item-processor/.yarnrc-lambda.yml
              - packages/webshop-item-processor/src/**
            webshop-processor:
              - yarn.lock
              - .github/workflows/deploy.yml
              - packages/webshop-processor/package.json
              - packages/webshop-processor/.yarnrc-lambda.yml
              - packages/webshop-processor/src/**
      - name: create-user
        id: create-user
        if: steps.changed-files-yaml.outputs.create-user_any_changed == 'true'
        run: |
          yarn workspace @centralbeans/create-user build
          version=$(yarn workspace @centralbeans/create-user deploy | jq -r '.Version')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Release create-user
        if: steps.changed-files-yaml.outputs.create-user_any_changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '@centralbeans/create-user@${{ steps.create-user.outputs.version }}'
          release_name: Release @centralbeans/create-user v${{ steps.create-user.outputs.version }}
          draft: false
          prerelease: false
      - name: delete-user
        id: delete-user
        if: steps.changed-files-yaml.outputs.delete-user_any_changed == 'true'
        run: |
          yarn workspace @centralbeans/delete-user build
          version=$(yarn workspace @centralbeans/delete-user deploy | jq -r '.Version')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Release delete-user
        if: steps.changed-files-yaml.outputs.delete-user_any_changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '@centralbeans/delete-user@${{ steps.delete-user.outputs.version }}'
          release_name: Release @centralbeans/delete-user v${{ steps.delete-user.outputs.version }}
          draft: false
          prerelease: false
      - name: flag-removed
        id: flag-removed
        if: steps.changed-files-yaml.outputs.flag-removed_any_changed == 'true'
        run: |
          yarn workspace @centralbeans/flag-removed build
          version=$(yarn workspace @centralbeans/flag-removed deploy | jq -r '.Version')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Release flag-removed
        if: steps.changed-files-yaml.outputs.flag-removed_any_changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '@centralbeans/flag-removed@${{ steps.flag-removed.outputs.version }}'
          release_name: Release @centralbeans/flag-removed v${{ steps.flag-removed.outputs.version }}
          draft: false
          prerelease: false
      - name: image-processor
        id: image-processor
        if: steps.changed-files-yaml.outputs.image-processor_any_changed == 'true'
        run: |
          yarn workspace @centralbeans/image-processor build
          version=$(yarn workspace @centralbeans/image-processor deploy | jq -r '.Version')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Release image-processor
        if: steps.changed-files-yaml.outputs.image-processor_any_changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '@centralbeans/image-processor@${{ steps.image-processor.outputs.version }}'
          release_name: Release @centralbeans/image-processor v${{ steps.image-processor.outputs.version }}
          draft: false
          prerelease: false
      - name: image-text-interpreter
        id: image-text-interpreter
        if: steps.changed-files-yaml.outputs.image-text-interpreter_any_changed == 'true'
        run: |
          yarn workspace @centralbeans/image-text-interpreter build
          version=$(yarn workspace @centralbeans/image-text-interpreter deploy | jq -r '.Version')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Release image-text-interpreter
        if: steps.changed-files-yaml.outputs.image-text-interpreter_any_changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '@centralbeans/image-text-interpreter@${{ steps.image-text-interpreter.outputs.version }}'
          release_name: Release @centralbeans/image-text-interpreter v${{ steps.image-text-interpreter.outputs.version }}
          draft: false
          prerelease: false
      - name: import-currencies
        id: import-currencies
        if: steps.changed-files-yaml.outputs.import-currencies_any_changed == 'true'
        run: |
          yarn workspace @centralbeans/import-currencies build
          version=$(yarn workspace @centralbeans/import-currencies deploy | jq -r '.Version')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Release import-currencies
        if: steps.changed-files-yaml.outputs.import-currencies_any_changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '@centralbeans/import-currencies@${{ steps.import-currencies.outputs.version }}'
          release_name: Release @centralbeans/import-currencies v${{ steps.import-currencies.outputs.version }}
          draft: false
          prerelease: false
      - name: invoke-flag-removed
        id: invoke-flag-removed
        if: steps.changed-files-yaml.outputs.invoke-flag-removed_any_changed == 'true'
        run: |
          yarn workspace @centralbeans/invoke-flag-removed build
          version=$(yarn workspace @centralbeans/invoke-flag-removed deploy | jq -r '.Version')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Release invoke-flag-removed
        if: steps.changed-files-yaml.outputs.invoke-flag-removed_any_changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '@centralbeans/invoke-flag-removed@${{ steps.invoke-flag-removed.outputs.version }}'
          release_name: Release @centralbeans/invoke-flag-removed v${{ steps.invoke-flag-removed.outputs.version }}
          draft: false
          prerelease: false
      - name: notifications
        id: notifications
        if: steps.changed-files-yaml.outputs.notifications_any_changed == 'true'
        run: |
          yarn workspace @centralbeans/notifications build
          version=$(yarn workspace @centralbeans/notifications deploy | jq -r '.Version')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Release notifications
        if: steps.changed-files-yaml.outputs.notifications_any_changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '@centralbeans/notifications@${{ steps.notifications.outputs.version }}'
          release_name: Release @centralbeans/notifications v${{ steps.notifications.outputs.version }}
          draft: false
          prerelease: false
      - name: record-roaster-webshop
        id: record-roaster-webshop
        if: steps.changed-files-yaml.outputs.record-roaster-webshop_any_changed == 'true'
        run: |
          yarn workspace @centralbeans/record-roaster-webshop build
          version=$(yarn workspace @centralbeans/record-roaster-webshop deploy | jq -r '.Version')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Release record-roaster-webshop
        if: steps.changed-files-yaml.outputs.record-roaster-webshop_any_changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '@centralbeans/record-roaster-webshop@${{ steps.record-roaster-webshop.outputs.version }}'
          release_name: Release @centralbeans/record-roaster-webshop v${{ steps.record-roaster-webshop.outputs.version }}
          draft: false
          prerelease: false
      - name: record-webshop-item
        id: record-webshop-item
        if: steps.changed-files-yaml.outputs.record-webshop-item_any_changed == 'true'
        run: |
          yarn workspace @centralbeans/record-webshop-item build
          version=$(yarn workspace @centralbeans/record-webshop-item deploy | jq -r '.Version')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Release record-webshop-item
        if: steps.changed-files-yaml.outputs.record-webshop-item_any_changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '@centralbeans/record-webshop-item@${{ steps.record-webshop-item.outputs.version }}'
          release_name: Release @centralbeans/record-webshop-item v${{ steps.record-webshop-item.outputs.version }}
          draft: false
          prerelease: false
      - name: record-webshop-item-details
        id: record-webshop-item-details
        if: steps.changed-files-yaml.outputs.record-webshop-item-details_any_changed == 'true'
        run: |
          yarn workspace @centralbeans/record-webshop-item-details build
          version=$(yarn workspace @centralbeans/record-webshop-item-details deploy | jq -r '.Version')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Release record-webshop-item-details
        if: steps.changed-files-yaml.outputs.record-webshop-item-details_any_changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '@centralbeans/record-webshop-item-details@${{ steps.record-webshop-item-details.outputs.version }}'
          release_name: Release @centralbeans/record-webshop-item-details v${{ steps.record-webshop-item-details.outputs.version }}
          draft: false
          prerelease: false
      - name: register-new-user
        id: register-new-user
        if: steps.changed-files-yaml.outputs.register-new-user_any_changed == 'true'
        run: |
          yarn workspace @centralbeans/register-new-user build
          version=$(yarn workspace @centralbeans/register-new-user deploy | jq -r '.Version')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Release register-new-user
        if: steps.changed-files-yaml.outputs.register-new-user_any_changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '@centralbeans/register-new-user@${{ steps.register-new-user.outputs.version }}'
          release_name: Release @centralbeans/register-new-user v${{ steps.register-new-user.outputs.version }}
          draft: false
          prerelease: false
      - name: send-registration-code
        id: send-registration-code
        if: steps.changed-files-yaml.outputs.send-registration-code_any_changed == 'true'
        run: |
          yarn workspace @centralbeans/send-registration-code build
          version=$(yarn workspace @centralbeans/send-registration-code deploy | jq -r '.Version')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Release send-registration-code
        if: steps.changed-files-yaml.outputs.send-registration-code_any_changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '@centralbeans/send-registration-code@${{ steps.send-registration-code.outputs.version }}'
          release_name: Release @centralbeans/send-registration-code v${{ steps.send-registration-code.outputs.version }}
          draft: false
          prerelease: false
      - name: webshop-item-processor
        id: webshop-item-processor
        if: steps.changed-files-yaml.outputs.webshop-item-processor_any_changed == 'true'
        run: |
          yarn workspace @centralbeans/webshop-item-processor build
          version=$(yarn workspace @centralbeans/webshop-item-processor deploy | jq -r '.Version')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Release webshop-item-processor
        if: steps.changed-files-yaml.outputs.webshop-item-processor_any_changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '@centralbeans/webshop-item-processor@${{ steps.webshop-item-processor.outputs.version }}'
          release_name: Release @centralbeans/webshop-item-processor v${{ steps.webshop-item-processor.outputs.version }}
          draft: false
          prerelease: false
      - name: webshop-processor
        id: webshop-processor
        if: steps.changed-files-yaml.outputs.webshop-processor_any_changed == 'true'
        run: |
          yarn workspace @centralbeans/webshop-processor build
          version=$(yarn workspace @centralbeans/webshop-processor deploy | jq -r '.Version')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Release webshop-processor
        if: steps.changed-files-yaml.outputs.webshop-processor_any_changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '@centralbeans/webshop-processor@${{ steps.webshop-processor.outputs.version }}'
          release_name: Release @centralbeans/webshop-processor v${{ steps.webshop-processor.outputs.version }}
          draft: false
          prerelease: false
