name: Release
on:
  schedule:
    - cron: '0 0 * * *'
permissions:
  contents: write
jobs:
  release:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Refresh static data
        env:
          TURSO_API_TOKEN: ${{ secrets.TURSO_API_TOKEN }}
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
          TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
        run: |
          yarn workspace @centralbeans/website build:scan:ci
          yarn workspace @centralbeans/website recommendations:ci
      - name: Commit changes
        continue-on-error: true
        run: |
          git config --global user.name 'Chealt GitHub automation'
          git config --global user.email 'info@centralbeans.com'
          git commit -am "Automated build"
          git push
