name: Release
on:
  schedule:
    - cron: '40 7 * * *'
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v6
      - name: Install dependencies
        run: yarn install
      - name: Refresh static data
        env:
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
          TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
        run: yarn workspace @chealt/coffee build:scan:ci
      - name: Commit changes
        run: |
          git config --global user.name 'Chealt GitHub automation'
          git config --global user.email 'info@centralbeans.com'
          git commit -am "Automated build"
          git push
