name: Trigger GitHub Action - Infra
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/triggerGithubActionInfra.yml'
      - 'packages/trigger-github-action/infra/**'
jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: deploy
        uses: aws-actions/aws-cloudformation-github-deploy@v2
        with:
          name: trigger-github-action-alarm
          template: packages/trigger-github-action/infra/alarm.yml
          capabilities: CAPABILITY_IAM
          fail-on-empty-changeset: false
